### ISSUE TITLE
Update to 1.6

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/freshrss_ynh#23] opened 2016-10-16 19:35 UTC
1.6 version is on testing phase right now: https://github.com/FreshRSS/FreshRSS/issues/1328

I create this issue to give you the information (in case you missed it), and as always, when you will update the repo with the new version, I will be happy to help you testing it :)

PS: and btw I'm currently making an extension for FreshRSS, adding a [reading time estimation](https://github.com/FreshRSS/FreshRSS/issues/1260) for each article. Maybe you will find it useful, feel free to try it :)

**Comment by plopoyop** [comment] 2016-10-17 06:59
Hey,
Tanks for the informations. 
I'll try to create a new branch quickly. With last update, it should be done faster than previous version. 
I'll try your extension. It will be a good test to see if they are kept on update.

**Comment by Alkarex** [comment] 2016-10-17 08:31
I do not think there is anything special with this new version regarding the install. Let me know if you face any difficulty.
And the future version 1.7 will have a command line https://github.com/FreshRSS/FreshRSS/milestone/20

**Comment by lapineige** [comment] 2016-10-17 19:35
> I'll try to create a new branch quickly. With last update, it should be done faster than previous version. 

Great :smiley:
As said, don't hesitate to ask for testing ;)

> I'll try your extension. It will be a good test to see if they are kept on update. 
A just fixed a small bug, it should no longer add the reading time several times ;)
Please let me know if you find it useful, or if there is any annoying bug ;)

**Comment by Alkarex** [comment] 2016-10-24 19:43
If it can help, FreshRSS 1.6 will have a Command-Line Interface https://github.com/FreshRSS/FreshRSS/pull/1338 (which was initially planned for 1.7)

**Comment by plopoyop** [comment] 2016-10-24 20:21
Hi
The only problem to make the update is that the install and update script need the release to be made.
I can't update the package until the release is done.

**Comment by Alkarex** [comment] 2016-10-24 20:31
1.6 is in testing phase, slightly delayed because I would like to land the CLI in it. I expect a release this week-end. Meanwhile, feedback welcome on /dev and the new CLI :-)

**Comment by lapineige** [comment] 2016-10-24 20:34
I don't think it's a problem: to be clear, I don't make this topic to get the 1.6 version before it's released. (I'm not here to stress you ;) )
That's for testing cases, and I use a VM for that, not my production server (well, a Raspberry Pi is not really a "production" server, but anyway^^).
I make it in order to give you the information when the version is almost ready for release - so you have time to test it, work on making the changes, and maybe found a blocking bug. Or not, you are doing this in your free time, again I'm not wanting to stress you.

And I think updating should not be done (except in a test branch) before the version is complete and release.

**Comment by plopoyop** [comment] 2016-10-24 20:44
I'll start again.
I can't test the update until the tar.gz is released (it's not a choice). 
The scripts don't download the sources via git but they download the tar.gz verify the checksum and extract it. So, there is no way to test before the release is done. 
When the release is done, I'll make a new branch for testing purpose.

**Comment by lapineige** [comment] 2016-10-24 20:51
I mean, for testing purposes, you could modify your version (manually, not by changing the update script) to test it, in case something specific to Yunohost (but not the update part) is broken with this new version.

**Comment by lapineige** [comment] 2016-10-30 21:27
FreshRSS 1.6 is out !! :) https://github.com/FreshRSS/FreshRSS/issues/1328#issuecomment-257172401

**Comment by plopoyop** [comment] 2016-10-31 11:45
Branche freshrss-1.6 should work the old way for testing.
https://github.com/YunoHost-Apps/freshrss_ynh/tree/freshrss-1.6

I'll try to update scripts to use cli interface as soon as possible

**Comment by lapineige** [comment] 2016-10-31 15:10
Updated successfully. Nothing to report right now.

> I'll try to update scripts to use cli interface as soon as possible

Just ping me when it's done, and I will test it ;)

**Comment by Alkarex** [comment] 2016-11-02 20:48
FYI, I have just released a hotfix 1.6.1 for a regression in 1.6.0 https://github.com/FreshRSS/FreshRSS/releases/tag/1.6.1

**Comment by plopoyop** [comment] 2016-11-02 21:07
I just pushed the update.
Thanks.

**Comment by lapineige** [comment] 2016-11-02 21:29
Thanks you both :)

**Comment by genma** [comment] 2016-11-08 15:19
Merge request to 1.6.1. support done https://github.com/YunoHost-Apps/freshrss_ynh/pull/25

**Comment by plopoyop** [comment] 2017-03-14 09:02
I just create a pull request for the feature/use-cli-interface branch :
https://github.com/YunoHost-Apps/freshrss_ynh/tree/feature/use-cli-interface

I made quite a lot of tests. On a virtual machine and using Ynh package checker.
The only test not working on package checker is the multi-instance installation that work on the virtual machine. I need to check the reason of the failure but it is working great for now. 

I am already using this branch on my personal instance of ynh.
I will merge before the end of the week and close this issue when it will be done.

**Comment by plopoyop** [comment] 2017-03-16 07:36
Merged : https://github.com/YunoHost-Apps/freshrss_ynh/pull/30

**Closed by plopoyop** 2017-03-16 07:36 UTC

**Comment by lapineige** [comment] 2017-03-16 20:01
Good news :)
I should be able to test it within a week.
