### ISSUE TITLE
FreshRSS 1.15.0

### ISSUE THREAD

**Issue by genma** [YunoHost-Apps/freshrss_ynh#84] opened 2019-11-05 13:12 UTC
FreshRSS 1.15.0 was released on Oct 31, 2019 https://github.com/FreshRSS/FreshRSS/releases/tag/1.15.0 Is it possible to have an update for this package ?

**Comment by Alkarex** [comment] 2019-11-05 13:14
FYI, we will have a quick fix 1.15.1 out shortly (today or tomorrow) https://github.com/FreshRSS/FreshRSS/pull/2633

**Comment by plopoyop** [comment] 2019-11-05 13:17
@Alkarex : I did not have the time to open an issue but I couldn't install the 1.15.0.
Even if I am calling the cli-install whith db mysql, I get an permission error for an sqlite file... 

Sorry, I am not at home to give you the exact error message. Maybe this evening.

**Comment by Alkarex** [comment] 2019-11-05 17:40
I can reproduce the following, if you do not have write access to `./data/users/*`

```sh
$ sudo touch /var/lib/docker/volumes/freshrss-data/_data/users/db.sqlite
$ sudo chmod a-rw /var/lib/docker/volumes/freshrss-data/_data/users/db.sqlite
$ sudo docker exec -it --user www-data freshrss_dev ./cli/do-install.php --default_user freshrss --db-type mysql --db-host mariadb --db-user freshrss --db-password freshrss --db-base freshrss
FreshRSS install…
PHP Fatal error:  Uncaught Minz_PDOConnectionException: Access to database is denied for `` (`sqlite:/var/www/FreshRSS/data/users//db.sqlite`) in /var/www/FreshRSS/lib/Minz/ModelPdo.php:91
Stack trace:
#0 /var/www/FreshRSS/app/Models/Factory.php(69): Minz_ModelPdo->__construct(false)
#1 /var/www/FreshRSS/lib/lib_install.php(92): FreshRSS_Factory::createDatabaseDAO()
#2 /var/www/FreshRSS/cli/do-install.php(85): checkDb()
#3 {main}
  thrown in /var/www/FreshRSS/lib/Minz/ModelPdo.php on line 91
```

Indeed, there should be no need to touch `/data/users/db.sqlite`, and I will try to fix that, but that directory should still be writeable :-)

**Comment by Alkarex** [comment] 2019-11-05 18:10
Hum, there may be a bigger problem. Looking into it

**Comment by plopoyop** [comment] 2019-11-05 18:26
The script is executed as root, there should not be permissions problem (but I tried to add the correct ownership).
the debug trace : 

```chown -R freshrss: /var/www/freshrss/data/
/var/www/freshrss/cli/do-install.php --default_user clement --auth_type http_auth --environment production --base_url https://yunohost.local/rss --title FreshRSS --api_enabled --db-type mysql --db-host localhost:3306 --db-user freshrss --db-password XXX --db-base freshrss
FreshRSS install…
PHP Fatal error:  Uncaught Minz_PDOConnectionException: Access to database is denied for `` (`sqlite:/var/www/freshrss/data/users//db.sqlite`) in /var/www/freshrss/lib/Minz/ModelPdo.php:91
Stack trace:
#0 /var/www/freshrss/app/Models/Factory.php(69): Minz_ModelPdo->__construct(false)
#1 /var/www/freshrss/lib/lib_install.php(92): FreshRSS_Factory::createDatabaseDAO()
#2 /var/www/freshrss/cli/do-install.php(85): checkDb()
#3 {main}
thrown in /var/www/freshrss/lib/Minz/ModelPdo.php on line 91
```

So, even if we use mysql, we need sqlite ? 
Should I add sqlite php extention as a dependency ?

**Comment by Alkarex** [comment] 2019-11-05 18:40
@plopoyop Adding SQLite would be a good idea as we have features, which depend on it in any case (e.g. export/import SQLite files).
But this made me find the root problem, which I am trying to fix :-)

**Comment by Alkarex** [comment] 2019-11-05 18:41
@plopoyop In your tests, the MySQL database is not created, right?

**Comment by plopoyop** [comment] 2019-11-05 18:42
The mysql database is created just before, so, it already exists

**Comment by plopoyop** [comment] 2019-11-05 18:54
It is working for me now, I'll wait for the 1.15.1 before updating the package.

**Comment by Alkarex** [comment] 2019-11-05 21:05
@plopoyop We had a regression preventing the auto-creation of databases (no problem if the database was already created in advance). This should be fixed in https://github.com/FreshRSS/FreshRSS/pull/2635
Would you be able to test? We can merge in /dev if it is easier

**Comment by plopoyop** [comment] 2019-11-05 21:15
When I don't add the sqlite extension, I have the same error message.
When I add the sqlite extension, the problem is solved.

**Comment by Alkarex** [comment] 2019-11-05 21:19
Thanks for the test @plopoyop 
Ok, I was about that it was strange to have the same error message 😄

**Comment by Alkarex** [comment] 2019-11-05 21:20
In any case it is good to add the SQLite extension, but I am still interested in a test without it and with the same setup than generated the original error you observed

**Comment by plopoyop** [comment] 2019-11-05 21:23
Sorry, as my edit said, my test was invalid.
After testing again, no error message with or without sqlite extension.
I'll still add it as dependency

**Comment by Alkarex** [comment] 2019-11-05 21:25
Excellent, thanks @plopoyop 👍

**Comment by Alkarex** [comment] 2019-11-06 21:05
@plopoyop Voilà :-) https://github.com/FreshRSS/FreshRSS/releases/tag/1.15.1

**Comment by plopoyop** [comment] 2019-11-06 21:17
@genma The package is now up to date in testing branch.
Have fun.

@Alkarex thanks for your work. as always :)

**Comment by Alkarex** [comment] 2019-11-06 21:18
P.S. : Pour la liste des paquets Debian, la liste la plus maintenue à jour est https://github.com/FreshRSS/FreshRSS/blob/dev/Docker/Dockerfile

**Closed by plopoyop** 2019-11-06 21:17 UTC

**Comment by Alkarex** [comment] 2019-11-06 21:19
P.P.S : What is missing in order to have an official YunoHost package?

**Comment by plopoyop** [comment] 2019-11-06 21:34
I update the depedencies list.
I don't really know the rules. I think there must be a community vote.
and the package must follow those rules : https://yunohost.org/#/packaging_apps_guidelines_fr
I think I would demand more investment from myself

**Comment by Alkarex** [comment] 2019-11-06 22:05
That looks reasonable, and please let us know @plopoyop if anything can be done on FreshRSS side to ease the packaging process

**Comment by Alkarex** [comment] 2019-11-08 18:06
1.15.2 coming soon (one more regression, hopefully the last...) https://github.com/FreshRSS/FreshRSS/milestones/1.15.2

**Comment by Alkarex** [comment] 2019-11-12 09:22
@plopoyop FreshRSS 1.15.2 released, with hopefully the last regressions closed https://github.com/FreshRSS/FreshRSS/releases/tag/1.15.2
